services:
  dashboard:
    build: .
    container_name: mi-dashboard
    ports:
      - "3222:8080"
    dns:
      - 1.1.1.3
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - DB_PATH=/app/data/dashboard.db
