services:
  dashora:
    image: netosvaltools/dashora:latest
    container_name: dashora
    dns:
      - 8.8.8.8
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - DB_PATH=/app/data/dashboard.db
